version: 2.1
jobs:
  build:
    docker:
    # docker run -it vusonbmt/dockerdemo:0.2 -c "/bin/bash"
      - image: vusonbmt/dockerdemo:0.3
    steps:
      - checkout
      - run:
          name: Build firmware
          command: |
           echo Hello Build
           export PATH="/opt/toolchains/gcc-arm-none-eabi-10.3-2021.10/bin:$PATH"
           arm-none-eabi-gcc --version
           type gcc
           git clone https://github.com/vusonbmt/stm32f103c8t6.git
           pwd
           mkdir /tmp/artifacts;
           cd stm32f103c8t6
           git submodule sync;
           git submodule update --init --recursive;
           cd rtos
           cp /home/FreeRTOSv10.0.1.zip $(pwd)
           unzip -q FreeRTOSv10.0.1.zip
           cd ..
           build_output_path=$(pwd)
           echo $build_output_path           
           make
           echo "Copy binary"
           cp $build_output_path/miniblink/*.bin /tmp/artifacts/
           cp $build_output_path/uart/*.bin /tmp/artifacts/
           cp $build_output_path/uarthwfc/*.bin /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts           
  unit-test:
    docker:
      - image: vusonbmt/dockerdemo:0.3
    steps:
      - checkout
      - run:
          name: Intall apt packages
          command: 'echo Hello UT'
      # - run:
      #     name: Build Unit Tests
      #     command: |
      #         cd test/rt/testbuild
      #         make
      # - run:
      #     name: Run Unit Tests
      #     command: |
      #         ./test/rt/testbuild/build/ch          
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - unit-test      