version: 2.1
jobs:
  build:
    docker:
    # docker run -it vusonbmt/dockerdemo:0.2 -c "/bin/bash"
      - image: vusonbmt/dockerdemo:0.2
    steps:
      - checkout
      - run:
          name: Build firmware
          command: |
           echo Hello Build
           apt-get install -y zip
           export PATH="/opt/toolchains/gcc-arm-none-eabi-10.3-2021.10/bin:$PATH"
           arm-none-eabi-gcc --version
           type gcc
           git clone https://github.com/vusonbmt/stm32f103c8t6.git
           cd stm32f103c8t6
           git clone https://github.com/libopencm3/libopencm3.git
           cd ..
           cd rtos
           wget https://liquidtelecom.dl.sourceforge.net/project/freertos/FreeRTOS/V10.0.1/FreeRTOSv10.0.1.zip
           unzip FreeRTOSv10.0.1.zip
           cd ..
           make
      
      # - store_artifacts:
      #     path: /tmp/artifacts/stm32f103-cmake-template-stdperiph.bin
      #     destination: stm32f103-cmake-template-stdperiph.bin
    
      # - store_artifacts:
      #     path: /tmp/artifacts/stm32f103-cmake-template-freertos.bin
      #     destination: stm32f103-cmake-template-freertos.bin
  unit-test:
    docker:
      - image: vusonbmt/dockerdemo:0.2
    steps:
      - checkout
      - run:
          name: Intall apt packages
          command: 'echo Hello UT'
      # - run:
      #     name: Build Unit Tests
      #     command: |
      #         cd test/rt/testbuild
      #         make
      # - run:
      #     name: Run Unit Tests
      #     command: |
      #         ./test/rt/testbuild/build/ch          
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - unit-test      